# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node

# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Elice-CI
# 이름. 이후에 CI가 동작하는 과정에서 이름으로 뜸.

on: # 어떤 경우에 아래 동작을 시행할 것인가?
  push: # 코드를 Push 할 때랑
    branches: [master]
  pull_request: # Merge Request가 날아올 때 쓴다...
    branches: [master]

jobs: # 실제 돌아갈 동작
  build: # 동작의 이름 (바꿔도 됨...)
    runs-on: ubuntu-latest # 우분투 최신 버전으로 돌린다.

    strategy: # 매개변수 이름을 지을 떄 주로 씀...
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps: # 돌아가는 동작들은 여기서 수행.
      # 저 마이너스가 각각의 동작을 의미함.
      - uses: actions/checkout@v2 # 플러그인 사용.
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2 # 플러그인 사용.
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm test
